# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{quality-measure-engine}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Marc Hadley", "Andy Gregorowicz"]
  s.date = %q{2011-01-21}
  s.description = %q{A library for extracting quality measure information from HITSP C32's and ASTM CCR's}
  s.email = %q{talk@projectpophealth.org}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "Rakefile",
    "VERSION",
    "js/map-reduce-utils.js",
    "js/underscore-min.js",
    "lib/qme/importer/code_system_helper.rb",
    "lib/qme/importer/entry.rb",
    "lib/qme/importer/generic_importer.rb",
    "lib/qme/importer/hl7_helper.rb",
    "lib/qme/importer/patient_importer.rb",
    "lib/qme/importer/property_matcher.rb",
    "lib/qme/importer/section_importer.rb",
    "lib/qme/map/map_reduce_builder.rb",
    "lib/qme/map/map_reduce_executor.rb",
    "lib/qme/measure/database_loader.rb",
    "lib/qme/measure/measure_loader.rb",
    "lib/qme/mongo_helpers.rb",
    "lib/qme_test.rb",
    "lib/quality-measure-engine.rb",
    "lib/tasks/measure.rake",
    "lib/tasks/mongo.rake",
    "measures/0001/0001_NQF_Asthma_Assessment.js",
    "measures/0001/0001_NQF_Asthma_Assessment.json",
    "measures/0032/0032_NQF_Cervical_Cancer_Screening.js",
    "measures/0032/0032_NQF_Cervical_Cancer_Screening.json",
    "measures/0033/components/0033_NQF_Chlamydia_Screening_All.js",
    "measures/0033/components/0033_NQF_Chlamydia_Screening_Older.js",
    "measures/0033/components/0033_NQF_Chlamydia_Screening_Younger.js",
    "measures/0033/components/root.json",
    "measures/0041/0041_NQF_Influenza_Immunization_For_Older_Adults.js",
    "measures/0041/0041_NQF_Influenza_Immunization_For_Older_Adults.json",
    "measures/0043/0043_NQF_Pneumonia_Vaccination_Status_For_Older_Adults.js",
    "measures/0043/0043_NQF_Pneumonia_Vaccination_Status_For_Older_Adults.json"
  ]
  s.homepage = %q{http://github.com/pophealth/quality-measure-engine}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A library for extracting quality measure information from HITSP C32's and ASTM CCR's}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mongo>, [">= 0"])
      s.add_runtime_dependency(%q<bson_ext>, [">= 0"])
      s.add_runtime_dependency(%q<rake>, [">= 0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
      s.add_runtime_dependency(%q<rubyzip>, [">= 0"])
      s.add_runtime_dependency(%q<mongo>, ["~> 1.1"])
      s.add_development_dependency(%q<jsonschema>, ["~> 2.0.0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.0.0"])
      s.add_development_dependency(%q<awesome_print>, ["~> 0.2.1"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.4.0"])
    else
      s.add_dependency(%q<mongo>, [">= 0"])
      s.add_dependency(%q<bson_ext>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<rubyzip>, [">= 0"])
      s.add_dependency(%q<mongo>, ["~> 1.1"])
      s.add_dependency(%q<jsonschema>, ["~> 2.0.0"])
      s.add_dependency(%q<rspec>, ["~> 2.0.0"])
      s.add_dependency(%q<awesome_print>, ["~> 0.2.1"])
      s.add_dependency(%q<jeweler>, ["~> 1.4.0"])
    end
  else
    s.add_dependency(%q<mongo>, [">= 0"])
    s.add_dependency(%q<bson_ext>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<rubyzip>, [">= 0"])
    s.add_dependency(%q<mongo>, ["~> 1.1"])
    s.add_dependency(%q<jsonschema>, ["~> 2.0.0"])
    s.add_dependency(%q<rspec>, ["~> 2.0.0"])
    s.add_dependency(%q<awesome_print>, ["~> 0.2.1"])
    s.add_dependency(%q<jeweler>, ["~> 1.4.0"])
  end
end

